[package]
name = "substreams-head-tracker"
version = "1.0.0"
edition = "2021"

[lib]
name = "substreams"
crate-type = ["cdylib"]

[dependencies]
prost = "0.11"
substreams = "0.5"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
